#!/usr/bin/with-contenv sh

[ -z "${WODBY_HOME}" ] && WODBY_HOME="/srv"
[ -z "${WODBY_APP_ROOT}" ] && WODBY_APP_ROOT="${WODBY_HOME}/docroot"
[ -z "${WODBY_APP_DOCROOT}" ] && WODBY_APP_DOCROOT="${WODBY_APP_ROOT}"
 
if [ ! -d "${WODBY_HOME}/conf/nginx" ] && [ ! -L "/etc/nginx" ];then
        mv "/etc/nginx" "${WODBY_HOME}/conf/"
        chown -R "${WODBY_USER}":"${WODBY_GROUP}" "${WODBY_HOME}/conf/nginx"
        ln -nsf "${WODBY_HOME}/conf/nginx" "/etc/nginx"
elif [ -d "${WODBY_HOME}/conf/nginx" ] && [ ! -L "/etc/nginx" ];then
        rm -rf /etc/nginx
        ln -nsf "${WODBY_HOME}/conf/nginx" "/etc/nginx"
fi
